name    'jhoblitt-policykit'
version '1.1.0'

author 'Joshua Hoblitt <jhoblitt@cpan.org>'
license 'GPLv3 + Apache'
project_page 'https://github.com/jhoblitt/puppet-policykit'
source 'https://github.com/jhoblitt/puppet-policykit.git'
summary 'Manages the policykit package'
description 'Manages the policykit package'
dependency 'puppetlabs/stdlib', '>= 3.0.0'
